# Generated by Django 4.1 on 2022-08-19 05:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                ("user_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("last_known_name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "slug",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_edited_at", models.DateTimeField(auto_now=True)),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.discorduser",
                    ),
                ),
            ],
        ),
    ]
