# Generated by Django 4.1 on 2022-08-19 06:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "slug",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_edited_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                ("user_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("last_known_name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CodeError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="A message.py describing this error."),
                ),
                (
                    "old_code_link",
                    models.URLField(help_text="A link to the original code."),
                ),
                (
                    "fixed_code_link",
                    models.URLField(help_text="A link to the fixed code."),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.case"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="case",
            name="created_for",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.discorduser"
            ),
        ),
    ]
