# Generated by Django 4.1 on 2022-08-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Entry",
            new_name="Case",
        ),
    ]
