# Generated by Django 4.1 on 2022-08-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discorduser",
            name="last_known_name",
            field=models.TextField(null=True),
        ),
    ]
