# Generated by Django 4.1 on 2022-08-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_codeerror_case"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codeerror",
            name="message",
        ),
        migrations.AddField(
            model_name="codeerror",
            name="description",
            field=models.TextField(
                default=1,
                help_text="A more in depth piece of text describing this error.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="codeerror",
            name="title",
            field=models.TextField(
                default=1, help_text="A short title describing this error."
            ),
            preserve_default=False,
        ),
    ]
