# Generated by Django 4.1 on 2022-08-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_entry_case"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message.py",
                    models.TextField(help_text="A message.py describing this error."),
                ),
                (
                    "old_code_link",
                    models.URLField(help_text="A link to the original code."),
                ),
                (
                    "fixed_code_link",
                    models.URLField(help_text="A link to the fixed code."),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.case"
                    ),
                ),
            ],
        ),
    ]
