# Generated by Django 4.1 on 2022-08-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_codeerror"),
    ]

    operations = [
        migrations.RenameField(
            model_name="codeerror",
            old_name="message.py",
            new_name="message",
        ),
    ]
